image:
  - Visual Studio 2017

environment:
  matrix:
  - platform: x64
    ARCH: x86_64
    BITNESS: 64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
  - platform: x86
    ARCH: i686
    BITNESS: 32
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-cmake

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

build_script:
  - set TARGET_ARTIFACT=bodged-%ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - pacman -S --needed --noconfirm base-devel zip %PACKAGES%
  - mkdir %TARGET_ARTIFACT%
  - >
    sh -c "$(cygpath -u '%APPVEYOR_BUILD_FOLDER%')/copy-blobs.sh $(cygpath -u '%APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%')"
  - zip -r %TARGET_ARTIFACT%.zip %TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT).zip
    name: target_artifact

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
