language: c++
sudo: true
dist: xenial

addons:
  apt:
    packages:
    - libstdc++6
    - lib32stdc++6
    - zip

env:
  global:
    - secure: QJF5M5wX40fnIFqYlRoBycibR3PIoWDUqkThE2HH3q1+sq7SjTssoD1OvNWSmThjc22zpTioZzSiIKRXdI8VKzpOH9Ynqpkg5kY7GMBE7PWfx2ZSAMCBUt6adGJaOgeiCTzj7E6HzxAzW7x9kqmNXGMRiQY6un1iaD5K1MpwkPtTvbVjw2xHzULVjoFDCtkt3wfPxP1BAR4vaPsGRc1/zR3tnuz2YTNp41HD8MERVHlrjOMmcELmBx1mfKHInHNNuG9W7AG/SgMVIn1tTQIeVzd4ee5LVbeILCBo+vM0itdgoTH519vztzX16PH2EWcVLKJUFcf9CAJ5VhNsCGkEKBW65cNMYJ6vkWIU2q69LgxwSZDrwn08lf3DnDd4GOqFSFo6o3kiJ61iDaFK1TiU39Upk0HgiusTRidk1y8+5Ox/okZN/RSUj5WcSxPZ3ftwb0NQ/5MZ65UFHsOuShy8CyH90UZ0x+IQp2MoGPcEOxg4boUl8ggayO/W0tjh5eJ6TfXCEu54coMCF3wCKqENZNXnyoEhxAEgBRowGBDPh2qAzuhjM8ZthWvDbZz0WvhegvbDIuwQ9+kLL8hJiu/P68yk0T2c/emTxLclZxa4sjMaThHMS+5IUytMavHMVD83SxOWrE92WbTYSyjmIR4MYXZE3Xm/00Hols8KxoHEoTQ=

matrix:
  include:
  - os: linux
    env:
      - ARCH=i686
      - BITNESS=32
  - os: linux
    env:
      - ARCH=x86_64
      - BITNESS=64
  - os: osx
    env:
      - ARCH=i686
      - BITNESS=32
  - os: osx
    env:
      - ARCH=x86_64
      - BITNESS=64

branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -q;

      sudo update-alternatives --remove-all gcc;
      sudo update-alternatives --remove-all g++;
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends install gcc-8 g++-8 \
        g++-8-multilib
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 10;
      sudo update-alternatives --set gcc /usr/bin/gcc-8;
      sudo update-alternatives --set g++ /usr/bin/g++-8;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update 1>/dev/null 2>&1;
       brew install gcc@8;
       brew link --overwrite --force gcc;
    fi

script:
  - export TARGET_DIR=bodged-$ARCH-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
  - export FULLT_TARGET_DIR=$TRAVIS_BUILD_DIR/$TARGET_DIR
  - mkdir -p $FULLT_TARGET_DIR
  - $TRAVIS_BUILD_DIR/copy-blobs.sh $FULLT_TARGET_DIR
  - zip -r $TARGET_DIR.zip $TARGET_DIR

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $TARGET_DIR.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
